jwt:
  secret: "xxxxxxx"
  path:
    - "/v1/comic/chapter/resource"  # 漫画资源
    - "/v1/user/UserInfo" # 用户信息
    - "/v1/user/collect" # 用户收藏
    - "/v1/user/isCollectComic" #用户是否收藏过
    - "/v1/user/UserCollects" #用户收藏列表
smtp:
  host: "smtp.qq.com"
  port: ":587"
  username: "xxxxxxx@qq.com"
  password: "xxxxxxx"


server:
  addr: '0.0.0.0:9000'
  cert: ''
  key: ''
  autoTls: false

database:
  user: 'root'
  pass: 'xxxxxxx'
  host: 'xxxxxxx'
  port: 3306
  dbname: 'heibox-comic'
  charset: 'utf8mb4'
  debug: true

mongo:
  user: 'xxxxxxx'
  pass: 'xxxxxxx'
  host: 'xxxxxxx'
  port: 27017

redis:
  addr: 'xxxxxxx:6379'
  password: 'xxxxxxx'
  db: 0

comic:
  storageDirectory: '/home/comic'

#采集器任务配置
adapter:
  # 包子漫画采集设置

  -
    name: "包子漫画"
    orderId: 1  #适配器变化
    sort: 999     #适配器采集顺序
    realTime: false
    comicChan: 1
    chapterChan: 2
    origin: "https://cn.baozimh.com"
    referer: ""
    maxTry: 1
    language: "zh"
    switch: true #是否开启,特殊脚本处理包子漫画的资源
    collect:
      - list
    cachePath: './dataCache'
    scope:
      -
    isPage: true
    state:
      - 2
    listTemplate:
      - "%v/classify?page=%v"
  -
    name: "动漫之家"
    orderId: 2  #适配器变化
    realTime: false
    sort: 1     #适配器采集顺序
    comicChan: 5
    chapterChan: 10
    origin: "https://manhua.dmzj.com"
    referer: ""
    maxTry: 5
    language: "zh"
    switch: true #是否开启
    collect:
      - list
      - resource
    cachePath: './dataCache'
    scope:
      -
    isPage: true
    state:
      - 1
      - 2
    listTemplate:
      - "https://sacg.dmzj.com/mh/index.php?c=category&m=doSearch&status=0&reader_group=0&zone=0&initial=all&type=0&p=%v&callback=search.renderResult"
  -
    name: "Mangabz"
    orderId: 6  #适配器变化
    realTime: false
    sort: 4    #适配器采集顺序
    comicChan: 5
    chapterChan: 5
    origin: "https://www.mangabz.com"
    referer: "https://www.mangabz.com"
    maxTry: 5
    language: "zh"
    switch: true #是否开启
    collect:
      - list
      - resource
    cachePath: ''
    scope:
      - "resources"
    isPage: true
    state:
      - 1
      - 2
    listTemplate:
      - "%v/manga-list-p%v"

  -
    name: "MangaStream"
    orderId: 7  #适配器变化
    realTime: false
    sort: 5    #适配器采集顺序
    comicChan: 5
    chapterChan: 5
    origin: "http://mangastream.mobi"
    referer: ""
    maxTry: 5
    language: "en"
    switch: true #是否开启
    collect:
      - list
      - resource
    cachePath: ''
    scope:
      -
    isPage: true
    state:
      - 1
      - 2
    listTemplate:
      - "%v/?page=%v"

  -
    name: "来漫画"
    orderId: 8  #适配器变化
    realTime: false
    sort: 3    #适配器采集顺序
    comicChan: 5
    chapterChan: 2
    origin: "https://www.laimanhua.net"
    referer: " https://www.laimanhua.net"
    maxTry: 5
    language: "zh"
    switch: true #是否开启
    collect:
      - list
      - resource
    cachePath: ''
    scope:
      - "cover"
      - "resources"
    isPage: true
    state:
      - 1
      - 2
    listTemplate:
      - "%v/kanmanhua/zaixian_rhmh/%v.html"
      - "%v/kanmanhua/zaixian_dlmh/%v.html"
      - "%v/kanmanhua/zaixian_ommh/%v.html"
      - "%v/kanmanhua/zaixian_gtmh/%v.html"

  - name: "都市漫画"
    orderId: 9  #适配器变化
    realTime: false
    sort: 2    #适配器采集顺序
    comicChan: 2
    chapterChan: 3
    origin: "https://www.dushimh.com"
    referer: ""
    maxTry: 5
    language: "zh"
    switch: true #是否开启
    collect:
      - list
      - resource
    cachePath: ''
    scope:
      -
    isPage: true
    state:
      - 1
      - 2
    listTemplate:
      - "%v/list/click/?page=%v"